name: flutter_thundertrack_stormg
description: "ThunderTrack - 去中心化交易跟单与社交日记应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 状态管理
  provider: ^6.1.2
  
  # 网络请求
  http: ^1.2.0
  dio: ^4.0.6
  web_socket_channel: ^2.4.0
  
  # JSON序列化
  json_annotation: ^4.9.0
  
  # 本地存储 (保留shared_preferences，移除hive)
  shared_preferences: ^2.2.2
  
  # UI组件
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  
  # 加密和安全
  crypto: ^3.0.3
  
  # 工具包
  intl: ^0.19.0
  url_launcher: ^6.2.4
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # JSON序列化代码生成
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # 添加资源文件夹
  assets:
    - assets/images/
    - assets/icons/
